SQLALCHEMY_TRACK_MODIFICATIONS = False
ALLOWED_METHODS = ['GET', 'POST', 'PUT', 'PATCH', 'DELETE']

SQLALCHEMY_DATABASE_URI = 'sqlite:///../app.db'
# SQLALCHEMY_DATABASE_URI = 'mysql+pymysql://user:pass@localhost:3306/dbname'

SECRET_KEY = ''
LOGIN_SALT = ''

BEHIND_PROXY = False
URL_PREFIX = ''
ADMIN_PASSWORD = ''
UPLOAD_PATH = ''
TEMP_FILE_PATH = ''
TEMP_FILE_SAVE = False

RECV_MAIL_ADDR = ''
SEND_MAIL_ADDR = ''
SEND_MAIL_PASSWD = ''
SEND_MAIL_SMTP_HOST = ''
SEND_MAIL_SMTP_PORT = 465
SEND_MAIL_SMTP_SSL = True
