TEMP_FILENAME_CHARSET = "0123456789abcdef"
ALLOWED_METHODS = ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']

BODY_TYPE_NORMAL = 1
BODY_TYPE_ESCAPED = 2
BODY_TYPE_TOO_LONG = 3

JWT_HEADER = "Authorization"
CONFIG_INIT_KEY = 'INITED'
